### PR TITLE
hide app from dock on mac

### LINKED ISSUE #3: BUG: App sticks on dock
I like the way the app is kept on the tray but there is no reason to keep it on the dock at the same time.

Here's how to remove it: https://github.com/tauri-apps/tauri/issues/6086

### PR DESCRIPTION
**Pull request by mariogarridopt**
fix #3

### CODE REVIEW

**Review by flaviodelgrosso — CHANGES_REQUESTED** [review]
`ActivationPolicy` only works on darwin. You can set `#[cfg(target_os = "macos")]` to allow conditional compilation on different platforms.

**Comment by mariogarridopt** [comment]
Added
`#[cfg(target_os = "macos")]`
I don't know much about Rust so xD Check my code out.
I did execute and build it without problems, but I'm on mac.

**Review by flaviodelgrosso — CHANGES_REQUESTED** [review]
Please, change `app.set_activation_policy(ActivationPolicy::Accessory);` to `app.set_activation_policy(tauri::ActivationPolicy::Accessory);`. Then remove the ActivationPolicy from the import from top to allow compilation on different platforms.

**Comment by flaviodelgrosso** [comment]
> Added `#[cfg(target_os = "macos")]` I don't know much about Rust so xD Check my code out. I did execute and build it without problems, but I'm on mac.

No problem :) Please, check the review

**Comment by mariogarridopt** [comment]
Oh, right no need for other platforms to import `ActivationPolicy` got it.

**Review by flaviodelgrosso — APPROVED** [review]

**Pull request merged**
